# Generated by Django 5.0.6 on 2024-06-06 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emaildetail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='custom_field',
            field=models.CharField(blank=True, max_length=22, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='salary',
            field=models.IntegerField(default=44),
        ),
    ]
