# Generated by Django 5.0.6 on 2024-06-07 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emaildetail', '0004_author_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='user',
        ),
        migrations.DeleteModel(
            name='user_profile',
        ),
    ]
